from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin


urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'pylab4.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^staticfiles/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.STATICFILES_DIRS, 'show_indexes': True}),
                       url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
                           {'document_root': settings.STATIC_ROOT}),
                       url(r'^admin/', include(admin.site.urls)),
                       (r'^$', 'purus.views.index'),
                       (r'^index/$', 'purus.views.index',),
                       (r'^logout/$', 'purus.views.logout'),
                       (r'^ajax_login_username/$', 'purus.views.ajax_login_username'),
                       (r'^ajax_register_username/$', 'purus.views.ajax_register_username'),
                       (r'^ajax_register_password/$', 'purus.views.ajax_register_password'),
                       (r'^ajax_register_password2/$', 'purus.views.ajax_register_password2'),
                       (r'^regist/$', 'purus.views.regist'),
                       (r'^ajax_regist/$', 'purus.views.ajax_regist'),
                       (r'^ajax_login/$', 'purus.views.ajax_login'),
                       (r'^post_add/$', 'forum.views.post_add'),
                       (r'^replays/(?P<post_id>\d+)/$', 'forum.views.replays'),
                       (r'^post_add14/(?P<parent_id>\d+)/$', 'forum.views.post_add14'),
                       (r'^replays14/(?P<post_id>\d+)/$', 'forum.views.replays14'),
                       (r'^web/$', 'blog.views.web'),
                       (r'^spider/$', 'blog.views.spider'),
                       (r'^tornado/$', 'blog.views.tornado'),
                       (r'^python/$', 'blog.views.python'),
                       (r'^notes/$', 'blog.views.notes'),
                       (r'^about/$', 'purus.views.about'),
                       (r'^blog/(?P<blog_id>\d+)/', include('blog.urls')),
                       (r'^blog/', include('blog.urls')),
                       (r'^catalog/$', 'blog.views.catalog'),
                       (r'^collection/$', 'purus.views.collection'),
                       (r'^warcraft/$', 'purus.views.warcraft'),
                       (r'^music/$', 'purus.views.music'),
                       (r'^metaweblog/$', 'blog.views.metaweblog'),
                       (r'^jsimg/$', 'purus.views.jsimg'),
                       (r'^ajax_jsimg/$', 'purus.views.ajax_jsimg'),
                       (r'^access_count_mon/$', 'purus.views.access_count_mon'),
                       (r'^access_count_day/$', 'purus.views.access_count_day'),
                       (r'^access_ip/$', 'purus.views.ips_to_sql'),
                       (r'^online_ips/$', 'purus.views.online_ips'),
)
